[package]
name = "db2any-example"
version = "0.1.0"
edition = "2024"

[dependencies]
pg2any_lib = "0.3.5"
tokio = { version = "1.47.1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1.41"
